### ISSUE TITLE
Doesn't start

### ISSUE THREAD

**Issue by krychevsk16** [ivanvza/arpy#13]
Basicly this happens:

sudo python arpy.py

python: can't open file 'arpy.py': [Errno 2] No such file or directory

Even if I cloned this git thing, still doesn't work

**Comment by ivanvza** [comment]
Hi @krychevsk16,

Are you in the same directory as the file arpy.py when you run `sudo python arpy.py` command?

**Comment by krychevsk16** [comment]
@ivanvza Still doesn't work:

Traceback (most recent call last):
  File "arpy.py", line 25, in <module>
    import scapy.all as scapy
  File "/Library/Python/2.7/site-packages/scapy/all.py", line 16, in <module>
    from scapy.arch import *
  File "/Library/Python/2.7/site-packages/scapy/arch/__init__.py", line 79, in <module>
    from scapy.arch.pcapdnet import *
  File "/Library/Python/2.7/site-packages/scapy/arch/pcapdnet.py", line 471, in <module>
    import dumbnet as dnet
ImportError: No module named dumbnet

**Comment by krychevsk16** [comment]
Nevermind, I installed the dumbnet (forgot original name), thanks for the program!
